// AUTO-GENERATED by scripts/optimize-shots.mjs — do not edit by hand.
export interface ShotMeta { w: number; h: number; lqip: string }
export const SHOTS: Record<string, ShotMeta> = {
  "map": {
    "w": 1920,
    "h": 1080,
    "lqip": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAgCdASoYAA4APu1iqU2ppaQiMAgBMB2JZQC06DDkYAD+8G/TUQsLtfQyLY5O1tVmYAAA"
  },
  "devices": {
    "w": 1920,
    "h": 1080,
    "lqip": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAQAwCdASoYAA4APu1kqU2ppaQiMAgBMB2JaQAAettbQAAA/vCEH/S6dIYm6jpgAAA="
  },
  "raidcost": {
    "w": 1920,
    "h": 1080,
    "lqip": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAgCdASoYAA4APu1iqU2tJaOiMAgBoB2JaQAAfj4AAP7wiq0/tXaxgX5gAA=="
  },
  "vending": {
    "w": 1920,
    "h": 1080,
    "lqip": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZwDKAC0HlvkAAP7wsmXrulde1f2MuRQo2HEAAAA="
  }
};
