// AUTO-GENERATED by scripts/optimize-shots.mjs — do not edit by hand.
export interface ShotMeta { w: number; h: number; widths: number[]; lqip: string }
export const SHOTS: Record<string, ShotMeta> = {
  "map": {
    "w": 1920,
    "h": 1080,
    "widths": [
      1920,
      1440,
      960
    ],
    "lqip": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAgCdASoYAA4APu1iqU2ppaQiMAgBMB2JZQC06DDkYAD+8G/TUQsLtfQyLY5O1tVmYAAA"
  },
  "devices": {
    "w": 1920,
    "h": 1080,
    "widths": [
      1920,
      1440,
      960
    ],
    "lqip": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAAAQAwCdASoYAA4APu1kqU2ppaQiMAgBMB2JaQAAettbQAAA/vCEH/S6dIYm6jpgAAA="
  },
  "raidcost": {
    "w": 1920,
    "h": 1080,
    "widths": [
      1920,
      1440,
      960
    ],
    "lqip": "data:image/webp;base64,UklGRjgAAABXRUJQVlA4ICwAAADQAgCdASoYAA4APu1iqU2tJaOiMAgBoB2JaQAAfj4AAP7wiq0/tXaxgX5gAA=="
  },
  "vending": {
    "w": 1920,
    "h": 1080,
    "widths": [
      1920,
      1440,
      960
    ],
    "lqip": "data:image/webp;base64,UklGRkIAAABXRUJQVlA4IDYAAAAwAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JZwDKAC0HlvkAAP7wsmXrulde1f2MuRQo2HEAAAA="
  },
  "detail-compound": {
    "w": 450,
    "h": 470,
    "widths": [
      440
    ],
    "lqip": "data:image/webp;base64,UklGRlQAAABXRUJQVlA4IEgAAADQAwCdASoYABkAPu1srVCppiQiqAqpMB2JZ2eeXAyJVoOb0KxuiEAA/vAgtPjz/ArLVfNFjmRbg3a4nAEnNz4oHbld06FaWAA="
  },
  "detail-events": {
    "w": 520,
    "h": 210,
    "widths": [
      440
    ],
    "lqip": "data:image/webp;base64,UklGRkgAAABXRUJQVlA4IDwAAABwAwCdASoYAAoAPu1kq04ppaQiMAgBMB2JZQDCgDBhpGX7CAAA/vBvxxf9HWWfF5J7mEmbAr20p6rXHAA="
  },
  "detail-devices": {
    "w": 940,
    "h": 300,
    "widths": [
      900,
      600,
      440
    ],
    "lqip": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAADQAgCdASoYAAgAPu1iqk2ppaQiMAgBMB2JaQAAe/QAAP7whOjI/JDAAAA="
  },
  "detail-raidcost": {
    "w": 1120,
    "h": 330,
    "widths": [
      900,
      600,
      440
    ],
    "lqip": "data:image/webp;base64,UklGRjwAAABXRUJQVlA4IDAAAADQAgCdASoYAAcAPu1iqU2ppaOjMAgBMB2JZwAAe/QAAP7wWVMQjH0Yei+R5gegAAA="
  },
  "detail-raidtable": {
    "w": 1120,
    "h": 230,
    "widths": [
      900,
      600,
      440
    ],
    "lqip": "data:image/webp;base64,UklGRjYAAABXRUJQVlA4ICoAAACwAgCdASoYAAUAPu1iqU2ppaOiMAgBMB2JaQAAeyAA/vCKZlh4Kt8AAAA="
  },
  "detail-market": {
    "w": 1180,
    "h": 340,
    "widths": [
      900,
      600,
      440
    ],
    "lqip": "data:image/webp;base64,UklGRjoAAABXRUJQVlA4IC4AAADQAgCdASoYAAcAPu1iqU2ppaQiMAgBMB2JaQAAfj4AAP7wspNqimO5qvCauDwA"
  }
};
