// AUTO-GENERATED by scripts/optimize-shots.mjs — do not edit by hand.
export interface ShotMeta { w: number; h: number; widths: number[]; lqip: string }
export const SHOTS: Record<string, ShotMeta> = {
  "map": {
    "w": 1456,
    "h": 865,
    "widths": [
      960,
      1440,
      1456
    ],
    "lqip": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAADQAwCdASoYAA4APu1iqU2ppaOiMAgBMB2JQBOgBDv4eDvsoeoF5gAA/vKrZIkybqBZ9GHLf+Vo7oLODGTw90b7ZGPMwyNtpR/O0yPGGgAAAA=="
  },
  "raidcost": {
    "w": 1438,
    "h": 1030,
    "widths": [
      960,
      1438
    ],
    "lqip": "data:image/webp;base64,UklGRkAAAABXRUJQVlA4IDQAAADwAgCdASoYABEAPu1wsFKppiSiqAgBMB2JaQAAPbY4AAD+8EBONxUUc9bU7VNpPonqsUAA"
  },
  "loadout": {
    "w": 1438,
    "h": 1030,
    "widths": [
      960,
      1438
    ],
    "lqip": "data:image/webp;base64,UklGRkQAAABXRUJQVlA4IDgAAAAQAwCdASoYABEAPu1srFEppaSiqAqpMB2JaQDQkBWcOQAA/vBAtfl9UnarwLr9d090dJvUC9AAAA=="
  },
  "recycler": {
    "w": 1438,
    "h": 1030,
    "widths": [
      960,
      1438
    ],
    "lqip": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAADwAgCdASoYABEAPu1uqlGtJiOiqAqpoB2JaQAAO30sQAD+8HCaL4P80attwEOTBZYQAA=="
  }
};
