/**
 * Converts the raw 1920x1080 product PNGs in ../branding/mockups into
 * responsive WebP for the site. Two widths per shot (1440 / 960) so the
 * browser can pick, plus a tiny blurred LQIP for instant paint.
 *
 * Run: node scripts/optimize-shots.mjs
 */
import sharp from 'sharp';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const SRC = path.resolve('../branding/mockups');
const OUT = path.resolve('public/shots');

// Only the genuinely-populated captures. The `raidar_hud_screen_*` files
// render as empty black frames and are deliberately excluded.
const SHOTS = [
  ['raidar_actual_app_screen_map.png', 'map'],
  ['raidar_actual_app_screen_devices.png', 'devices'],
  ['raidar_actual_app_screen_raidcost.png', 'raidcost'],
  ['raidar_actual_app_screen_vending.png', 'vending'],
];

const WIDTHS = [1440, 960];

await mkdir(OUT, { recursive: true });

const manifest = {};

for (const [file, slug] of SHOTS) {
  const src = path.join(SRC, file);
  if (!existsSync(src)) {
    console.error(`MISSING: ${src}`);
    process.exitCode = 1;
    continue;
  }
  const buf = await readFile(src);
  const meta = await sharp(buf).metadata();

  for (const w of WIDTHS) {
    const outPath = path.join(OUT, `${slug}-${w}.webp`);
    const info = await sharp(buf)
      .resize({ width: w, withoutEnlargement: true })
      .webp({ quality: 82, effort: 6 })
      .toFile(outPath);
    console.log(`${slug}-${w}.webp  ${(info.size / 1024).toFixed(0)} KB  ${info.width}x${info.height}`);
  }

  // Inline LQIP: 24px wide, blurred, base64 — paints before the real file lands.
  const lqip = await sharp(buf)
    .resize({ width: 24 })
    .blur(1.1)
    .webp({ quality: 40 })
    .toBuffer();

  manifest[slug] = {
    w: meta.width,
    h: meta.height,
    lqip: `data:image/webp;base64,${lqip.toString('base64')}`,
  };
}

await writeFile(
  path.resolve('src/lib/shots.ts'),
  `// AUTO-GENERATED by scripts/optimize-shots.mjs — do not edit by hand.\n` +
    `export interface ShotMeta { w: number; h: number; lqip: string }\n` +
    `export const SHOTS: Record<string, ShotMeta> = ${JSON.stringify(manifest, null, 2)};\n`,
  'utf8',
);

console.log(`\nWrote src/lib/shots.ts with ${Object.keys(manifest).length} entries.`);
